# Cleaning

### Data exploration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from functions import *

In [3]:
# Open the raw datasets
# Immo datas
immo = pd.read_csv('../../Datasets/raw_immo_scrap.csv', sep=',', na_values=('None', 'no price'))

# localiy to commune
PC_commune = pd.read_csv('../../Datasets/liste-des-codes-postaux-belges-fr.csv', sep=';')

# Communes with polygons
commune_data = pd.read_csv('../../Datasets/communes-belges-2019.csv', sep = ';')
# https://public.opendatasoft.com/explore/dataset/communes-belges-2019/table/

In [4]:
immo.shape

(52077, 20)

In [5]:
immo

,locality,type_of_property,subtype_of_property,price,type_of_sale,number_of_rooms,house_area,fully_equipped_kitchen,furnished,open_fire,terrace,terrace_area,garden,garden_area,surface_of_the_land,surface_of_the_plot_of_land,number_of_facades,swimming_pool,state_of_the_building,construction_year
0,1050,house,house,340000.0,for sale,6.0,203.0,1,NaN,0,1,NaN,0,NaN,95.0,NaN,2.0,0,to be done up,1901.0
1,1880,house,villa,525000.0,for sale,6.0,250.0,1,NaN,0,1,40.0,1,430.0,826.0,NaN,4.0,0,as new,1992.0
2,4900,house,exceptional property,550000.0,for sale,11.0,475.0,1,NaN,0,1,NaN,1,1400.0,1543.0,NaN,4.0,0,good,1853.0
3,7912,house,villa,550000.0,for sale,4.0,325.0,1,NaN,0,1,125.0,1,2333.0,3570.0,NaN,4.0,0,good,1918.0
4,6032,house,house,550000.0,for sale,5.0,400.0,1,NaN,0,1,80.0,1,500.0,616.0,NaN,3.0,0,as new,1977.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52072,3120,house,house,455496.0,for sale,3.0,NaN,0,NaN,0,0,NaN,0,NaN,695.0,NaN,NaN,0,NaN,NaN
52073,1800,house,house,451650.0,for sale,3.0,NaN,0,NaN,0,0,NaN,0,NaN,550.0,NaN,3.0,0,NaN,NaN
52074,2018,house,house,488000.0,for sale,3.0,145.0,0,NaN,0,0,NaN,1,48.0,0.0,NaN,3.0,0,NaN,NaN
52075,9140,house,house,455000.0,for sale,3.0,NaN,0,NaN,0,0,NaN,0,NaN,1202.0,NaN,4.0,0,NaN,NaN
52076,9620,house,house,469000.0,for sale,3.0,NaN,0,NaN,0,0,NaN,0,NaN,1500.0,NaN,4.0,0,NaN,NaN

In [6]:
immo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52077 entries, 0 to 52076
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   locality                     52077 non-null  int64
 1   type_of_property             52077 non-null  object
 2   subtype_of_property          52077 non-null  object
 3   price                        52007 non-null  float64
 4   type_of_sale                 52077 non-null  object
 5   number_of_rooms              52075 non-null  float64
 6   house_area                   43445 non-null  float64
 7   fully_equipped_kitchen       52077 non-null  int64
 8   furnished                    0 non-null      float64
 9   open_fire                    52077 non-null  int64
 10  terrace                      52077 non-null  int64
 11  terrace_area                 17518 non-null  float64
 12  garden                       52077 non-null  int64
 13  garden_area                  8453 non-null   float64
 14  surface_of_the_land          29353 non-null  float64
 15  surface_of_the_plot_of_land  0 non-null      float64
 16  number_of_facades            38427 non-null  float64
 17  swimming_pool                52077 non-null  int64
 18  state_of_the_building        38491 non-null  object
 19  construction_year            30708 non-null  float64
dtypes: float64(10), int64(6), object(4)
memory usage: 7.9+ MB

In [7]:
immo.describe(include='all').transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
locality,52077,NaN,NaN,NaN,5406.22,2958.59,1000,2600,5060,8430,9992
type_of_property,52077,2,house,29353,NaN,NaN,NaN,NaN,NaN,NaN,NaN
subtype_of_property,52077,24,house,22100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,52007,NaN,NaN,NaN,305756,167907,1000,195000,267000,370000,950000
type_of_sale,52077,1,for sale,52077,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_of_rooms,52075,NaN,NaN,NaN,2.81458,2.20298,0,2,3,3,204
house_area,43445,NaN,NaN,NaN,153.721,183.355,1,90,128,185,31700
fully_equipped_kitchen,52077,NaN,NaN,NaN,0.652284,0.47625,0,0,1,1,1
furnished,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
open_fire,52077,NaN,NaN,NaN,0.0469497,0.211533,0,0,0,0,1
terrace,52077,NaN,NaN,NaN,0.563569,0.495947,0,0,1,1,1
terrace_area,17518,NaN,NaN,NaN,23.6743,30.0829,1,9,16,29,1150
garden,52077,NaN,NaN,NaN,0.289859,0.453701,0,0,0,1,1
garden_area,8453,NaN,NaN,NaN,712.1,4311.45,1,70,184,535,312600
surface_of_the_land,29353,NaN,NaN,NaN,992.812,5026.02,0,142,350,810,400000
surface_of_the_plot_of_land,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_of_facades,38427,NaN,NaN,NaN,2.76602,0.859295,1,2,3,4,4
swimming_pool,52077,NaN,NaN,NaN,0.0159571,0.125311,0,0,0,0,1
state_of_the_building,38491,6,as new,14826,NaN,NaN,NaN,NaN,NaN,NaN,NaN
construction_year,30708,NaN,NaN,NaN,1984.11,37.3152,1755,1964,1992,2018,2048

In [8]:
immo.dtypes

locality                         int64
type_of_property                object
subtype_of_property             object
price                          float64
type_of_sale                    object
number_of_rooms                float64
house_area                     float64
fully_equipped_kitchen           int64
furnished                      float64
open_fire                        int64
terrace                          int64
terrace_area                   float64
garden                           int64
garden_area                    float64
surface_of_the_land            float64
surface_of_the_plot_of_land    float64
number_of_facades              float64
swimming_pool                    int64
state_of_the_building           object
construction_year              float64
dtype: object

In [9]:
immo.isnull().sum()

locality                           0
type_of_property                   0
subtype_of_property                0
price                             70
type_of_sale                       0
number_of_rooms                    2
house_area                      8632
fully_equipped_kitchen             0
furnished                      52077
open_fire                          0
terrace                            0
terrace_area                   34559
garden                             0
garden_area                    43624
surface_of_the_land            22724
surface_of_the_plot_of_land    52077
number_of_facades              13650
swimming_pool                      0
state_of_the_building          13586
construction_year              21369
dtype: int64

### Cleaning

###### Drop useless columns (not filled/all the same)

In [10]:
immo = immo.drop(["furnished", "surface_of_the_plot_of_land", "type_of_sale"], axis=1)

###### Drop rows with null in essential columns

In [11]:
immo.dropna(axis=0, inplace=True, subset=['house_area'])
immo.dropna(axis=0, inplace=True, subset=['price'])
immo.isna().sum()

locality                      0
type_of_property              0
subtype_of_property           0
price                         0
number_of_rooms               2
house_area                    0
fully_equipped_kitchen        0
open_fire                     0
terrace                       0
terrace_area              26488
garden                        0
garden_area               35339
surface_of_the_land       20649
number_of_facades         11064
swimming_pool                 0
state_of_the_building     10615
construction_year         16527
dtype: int64

###### Replace some non essential unknow values by 0, we will rework them after

In [12]:
immo['terrace_area'] = immo['terrace_area'].fillna(0)
immo['garden_area'] = immo['garden_area'].fillna(0)
immo['surface_of_the_land'] = immo['surface_of_the_land'].fillna(0)

###### Drop Duplicates

In [13]:
immo.shape

(43401, 17)

In [14]:
immo = immo.drop_duplicates()

In [15]:
immo.shape

(42368, 17)

###### Setting the type

In [16]:
immo.dtypes

locality                    int64
type_of_property           object
subtype_of_property        object
price                     float64
number_of_rooms           float64
house_area                float64
fully_equipped_kitchen      int64
open_fire                   int64
terrace                     int64
terrace_area              float64
garden                      int64
garden_area               float64
surface_of_the_land       float64
number_of_facades         float64
swimming_pool               int64
state_of_the_building      object
construction_year         float64
dtype: object

In [17]:
immo['price'] = immo['price'].astype('int64')
immo['number_of_rooms'] = immo['number_of_rooms'].astype('Int64')
immo['house_area'] = immo['house_area'].astype('int64')
immo['terrace_area'] = immo['terrace_area'].astype('Int64')
immo['garden_area'] = immo['garden_area'].astype('Int64')
immo['surface_of_the_land'] = immo['surface_of_the_land'].astype('Int64')
immo['number_of_facades'] = immo['number_of_facades'].astype('Int64')
immo['construction_year'] = immo['construction_year'].astype('Int64')

In [18]:
immo.dtypes

locality                   int64
type_of_property          object
subtype_of_property       object
price                      int64
number_of_rooms            Int64
house_area                 int64
fully_equipped_kitchen     int64
open_fire                  int64
terrace                    int64
terrace_area               Int64
garden                     int64
garden_area                Int64
surface_of_the_land        Int64
number_of_facades          Int64
swimming_pool              int64
state_of_the_building     object
construction_year          Int64
dtype: object

###### Rename locality as we will have another locality

In [19]:
immo.rename(columns={'locality': 'zip'}, inplace=True)

###### Decision : wich variables are essentials ?

Arbitrarily, I decided that the locality, the price, the house area, the surface of the land and the state of the building are essentials.
Others columns will be cleaned on demand only, but these 5 will always be cleaned (but some ouliers will be cut off based on other categories).

###### Locality

In [26]:
PC_commune

,Code postal,Localité,Sous-commune,Commune principale,Province
0,5670,Mazée,Oui,VIROINVAL,Namur
1,1860,MEISE,Non,MEISE,Brabant Flamand
2,9700,Melden,Oui,OUDENAARDE,Flandre-Orientale
3,1370,Mélin,Oui,JODOIGNE,Brabant Wallon
4,4520,Moha,Oui,WANZE,Liège
...,...,...,...,...,...
2820,8400,Zandvoorde,Oui,OOSTENDE,Flandre-Occidentale
2821,3800,Zepperen,Oui,SINT-TRUIDEN,Limbourg
2822,2230,HERSELT,Non,HERSELT,Anvers
2823,6987,Hodister,Oui,RENDEUX,Luxembourg
2824,3746,Hoelbeek,Oui,BILZEN,Limbourg

In [27]:
PC_commune.rename(columns={'Code postal' : 'zip',
                           'Localité' : 'locality',
                        'Commune principale': 'commune',
                        'Province' : 'province'}, inplace=True)

In [28]:
PC_commune = PC_commune.drop(['Sous-commune'], axis=1)

In [29]:
PC_commune.isnull().sum()

zip          0
locality     0
commune     44
province    44
dtype: int64

In [30]:
PC_commune[PC_commune['commune'].isnull()]

       zip                                           locality commune province
115   1733                                        HighCo DATA     NaN      NaN
219   5012                                   Parlement Wallon     NaN      NaN
239   1049                      Union Européenne - Commission     NaN      NaN
240   1048                         Union Européenne - Conseil     NaN      NaN
315   5589                                            Jemelle     NaN      NaN
739   1804                                           Cargovil     NaN      NaN
796   1934         Office Exchange Brussels Airport Remailing     NaN      NaN
838   1008                          Chambre des Représentants     NaN      NaN
890   1031                 Organisations Sociales Chrétiennes     NaN      NaN
909   1011                                   Vlaams parlement     NaN      NaN
912   1043                                                VRT     NaN      NaN
1012  7511                                    Vitrine Magique     NaN      NaN
1146  1005    Assemblée Réunie de la Commission Communautaire     NaN      NaN
1226  7513                                        Yves Rocher     NaN      NaN
1265  9099                                             Gent X     NaN      NaN
1362  1935                                  Corporate Village     NaN      NaN
1451  7512                                        Yves Rocher     NaN      NaN
1460   612                                      Saint-Nicolas     NaN      NaN
1619  4099                                            Liège X     NaN      NaN
1672  6099                                        Charleroi X     NaN      NaN
1735  7010                                              SHAPE     NaN      NaN
1821  9075                                         CSM Gent X     NaN      NaN
1928  1033                                            RTL-TVI     NaN      NaN
2048  1099                                        Bruxelles X     NaN      NaN
2094  1035       Ministère de la Région de Bruxelles Capitale     NaN      NaN
2207  1009                                  Senat de Belgique     NaN      NaN
2235  6075                                    CSM Charleroi X     NaN      NaN
2252  1041                         International Press Center     NaN      NaN
2284  1012               Parlement de la Communauté française     NaN      NaN
2309  1818                                                VTM     NaN      NaN
2354  1046                   European External Action Service     NaN      NaN
2384  1047                                 Parlement Européen     NaN      NaN
2391  5010                                       SA SudPresse     NaN      NaN
2421  2099                                        Antwerpen x     NaN      NaN
2485  1101                                           Scanning     NaN      NaN
2569  1100                                         Postcheque     NaN      NaN
2605  7510                                          3 Suisses     NaN      NaN
2606  1105                                            ACTISOC     NaN      NaN
2609  1007  Assemblée de la Commission Communautaire Franç...     NaN      NaN
2619  1931                                           Brucargo     NaN      NaN
2682  1110                                               OTAN     NaN      NaN
2689  1006          Raad van de Vlaamse Gemeenschapscommissie     NaN      NaN
2791  1044                                               RTBF     NaN      NaN
2798  1212                                       SPF Mobilité     NaN      NaN

In [31]:
PC_commune.dropna(axis=0, inplace=True, subset=['commune'])
PC_commune.reset_index(drop=True, inplace=True)

In [32]:
PC_commune['commune'].value_counts()

TOURNAI               30
NAMUR                 25
TONGEREN              19
ATH                   19
MONS                  19
                      ..
EDEGEM                 1
SCHOTEN                1
EEKLO                  1
VORSELAAR              1
RHODE-SAINT-GENÈSE     1
Name: commune, Length: 581, dtype: int64

In [33]:
PC_commune[PC_commune['locality'] == "SAINT-NICOLAS"]

      zip       locality        commune province
688  4420  SAINT-NICOLAS  SAINT-NICOLAS    Liège

In [34]:
PC_commune.iloc[688, [0]] = 'Saint-Nicolas'

In [36]:
immo = pd.merge(immo, PC_commune, on=['zip'], how='inner')

In [37]:
immo

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,terrace_area,garden,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,construction_year,locality,commune,province
0,1050,house,house,340000,6,203,1,0,1,0,0,0,95,2,0,to be done up,1901,IXELLES,IXELLES,Bruxelles (19 communes)
1,1050,house,mixed use building,520000,4,200,0,0,0,0,0,0,69,2,0,to renovate,1940,IXELLES,IXELLES,Bruxelles (19 communes)
2,1050,house,house,599000,4,160,1,0,1,0,1,55,100,2,0,to be done up,1898,IXELLES,IXELLES,Bruxelles (19 communes)
3,1050,house,house,599000,3,160,1,0,1,15,1,60,130,2,0,good,1953,IXELLES,IXELLES,Bruxelles (19 communes)
4,1050,house,house,575000,3,171,0,0,0,0,0,0,46,2,0,just renovated,<NA>,IXELLES,IXELLES,Bruxelles (19 communes)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121066,1472,house,villa,475000,5,215,1,0,1,0,0,0,1550,<NA>,1,good,<NA>,Vieux-Genappe,GENAPPE,Brabant Wallon
121067,1461,house,villa,499000,5,275,1,0,1,0,1,0,1561,4,0,NaN,1983,Haut-Ittre,ITTRE,Brabant Wallon
121068,6686,house,chalet,495000,4,227,1,0,1,35,1,4400,4446,4,0,good,1983,Flamierge,BERTOGNE,Luxembourg
121069,1761,house,villa,495000,4,235,1,0,0,0,1,0,488,4,0,NaN,2020,Borchtlombeek,ROOSDAAL,Brabant Flamand
121070,3381,house,house,485000,3,220,0,0,1,19,0,0,1019,4,0,good,1976,Kapellen,GLABBEEK,Brabant Flamand

In [38]:
immo['region'] = immo['province'].apply(get_region)

In [39]:
immo['commune'].value_counts()

KNOKKE-HEIST    2791
OUDENAARDE      2520
TONGEREN        2508
LIÈGE           2471
OOSTENDE        2271
                ...
FLOBECQ            4
RUMES              4
AS                 3
KALMTHOUT          3
HERSTAPPE          1
Name: commune, Length: 580, dtype: int64

###### Rank the communes by mean(price)

In [40]:
Dict_city_rank_price = immo.groupby('commune')['price'].mean().sort_values().rank().to_dict()

In [41]:
Dict_city_rank_price

{'QUIÉVRAIN': 1.0,
 'DOUR': 2.0,
 'MOMIGNIES': 3.0,
 'FROIDCHAPELLE': 4.0,
 'ANTOING': 5.0,
 'COLFONTAINE': 6.0,
 'LIMBOURG': 7.0,
 'AMBLÈVE': 8.0,
 'QUAREGNON': 9.0,
 'FRAMERIES': 10.0,
 'RENDEUX': 11.0,
 'SAINT-NICOLAS': 12.0,
 'VIROINVAL': 13.0,
 'ERQUELINNES': 14.0,
 'BOUSSU': 15.0,
 'HASTIÈRE': 16.0,
 'CERFONTAINE': 17.0,
 'FARCIENNES': 18.0,
 'CHARLEROI': 19.0,
 'HENSIES': 20.0,
 'DISON': 21.0,
 'FLORENVILLE': 22.0,
 'SIVRY-RANCE': 23.0,
 'ENGIS': 24.0,
 'MERBES-LE-CHÂTEAU': 25.0,
 'CHÂTELET': 26.0,
 'AMAY': 27.0,
 'SERAING': 28.0,
 'BINCHE': 29.0,
 'BEAUMONT': 30.0,
 'FLEURUS': 31.0,
 'SAINT-HUBERT': 32.0,
 'WALCOURT': 33.0,
 'ANDERLUES': 34.0,
 'MORLANWELZ': 35.0,
 'LA LOUVIÈRE': 36.0,
 'BOUILLON': 37.0,
 'MONS': 38.0,
 'PHILIPPEVILLE': 39.0,
 'SAINT-GHISLAIN': 40.0,
 'BEAURAING': 41.0,
 'COURCELLES': 42.0,
 'ANTHISNES': 43.0,
 'CHIÈVRES': 44.0,
 'GRÂCE-HOLLOGNE': 45.0,
 'ROUVROY': 46.0,
 'TROOZ': 47.0,
 'MANAGE': 48.0,
 "FONTAINE-L'EVÊQUE": 49.0,
 'HOTTON': 50.0,
 'HEUVELLAND': 51.0,
 'BIÈVRE': 52.0,
 'VERVIERS': 53.0,
 'COUVIN': 54.0,
 'BULLANGE': 55.0,
 'SAINT-VITH': 56.0,
 'RUMES': 57.0,
 'BERTRIX': 58.0,
 'COMBLAIN-AU-PONT': 59.0,
 'BRAINE-LE-COMTE': 60.0,
 'GEDINNE': 61.0,
 'MIDDELKERKE': 62.0,
 'ESTINNES': 63.0,
 'SOIGNIES': 64.0,
 'LA ROCHE-EN-ARDENNE': 65.0,
 'SAINTE-ODE': 66.0,
 'FAUVILLERS': 67.0,
 'FLORENNES': 68.0,
 'PEPINSTER': 69.0,
 'ANS': 70.0,
 'JEMEPPE-SUR-SAMBRE': 71.0,
 'BRUGELETTE': 72.0,
 'SOMME-LEUZE': 73.0,
 'QUÉVY': 74.0,
 'CINEY': 75.0,
 'HERBEUMONT': 76.0,
 'VRESSE-SUR-SEMOIS': 77.0,
 'FLÉMALLE': 78.0,
 'SAMBREVILLE': 79.0,
 'HOUFFALIZE': 80.0,
 'HUY': 81.0,
 'MARCHE-EN-FAMENNE': 82.0,
 'ANHÉE': 83.0,
 'TELLIN': 84.0,
 'LANDEN': 85.0,
 'LA CALAMINE': 86.0,
 'BURG-REULAND': 87.0,
 'WERVIK': 88.0,
 'LIÈGE': 89.0,
 'HOESELT': 90.0,
 'FLÉRON': 91.0,
 'MUSSON': 92.0,
 'ANDENNE': 93.0,
 'HAMOIR': 94.0,
 'ELLEZELLES': 95.0,
 'HERSTAL': 96.0,
 'FEXHE-LE-HAUT-CLOCHER': 97.0,
 'VIELSALM': 98.0,
 'OUDSBERGEN': 99.0,
 'OREYE': 100.0,
 'AVELGEM': 101.0,
 'MENEN': 102.0,
 'EREZÉE': 103.0,
 'ATH': 104.0,
 'DONCEEL': 105.0,
 'THUIN': 106.0,
 'BERNISSART': 107.0,
 'ONHAYE': 108.0,
 'NASSOGNE': 109.0,
 'ROCHEFORT': 110.0,
 'BREDENE': 111.0,
 'ZOUTLEEUW': 112.0,
 'PONT-À-CELLES': 113.0,
 'FOSSES-LA-VILLE': 114.0,
 'CHIMAY': 115.0,
 'WAREMME': 116.0,
 'DE PANNE': 117.0,
 'BASSENGE': 118.0,
 'CLAVIER': 119.0,
 'LÉGLISE': 120.0,
 'LEOPOLDSBURG': 121.0,
 'ECAUSSINNES': 122.0,
 'NEUFCHÂTEAU': 123.0,
 'HECHTEL-EKSEL': 124.0,
 'HONNELLES': 125.0,
 'PLOMBIÈRES': 126.0,
 'PALISEUL': 127.0,
 'WEVELGEM': 128.0,
 'HERSTAPPE': 129.0,
 'OUPEYE': 130.0,
 'LESSINES': 131.0,
 'GINGELOM': 132.0,
 'VIRTON': 133.0,
 'DINANT': 134.0,
 'KUURNE': 135.0,
 'WANZE': 136.0,
 'RENAIX': 137.0,
 'PECQ': 138.0,
 'METTET': 139.0,
 'KOEKELBERG': 140.0,
 'KORTEMARK': 141.0,
 'CELLES': 142.0,
 'DOISCHE': 143.0,
 'MODAVE': 144.0,
 'BURDINNE': 145.0,
 'AYWAILLE': 146.0,
 'MOUSCRON': 147.0,
 'GEETBETS': 148.0,
 'SAINT-GEORGES-SUR-MEUSE': 149.0,
 'POPERINGE': 150.0,
 'VAUX-SUR-SÛRE': 151.0,
 'VLETEREN': 152.0,
 'BLANKENBERGE': 153.0,
 'HAMME': 154.0,
 'HEERS': 155.0,
 'ZWEVEGEM': 156.0,
 'FERRIÈRES': 157.0,
 'ZELZATE': 158.0,
 'SOUMAGNE': 159.0,
 'GEER': 160.0,
 'VISÉ': 161.0,
 'CRISNÉE': 162.0,
 'HARELBEKE': 163.0,
 'BEYNE-HEUSAY': 164.0,
 'VILLERS-LE-BOUILLET': 165.0,
 'BASTOGNE': 166.0,
 'HAVELANGE': 167.0,
 'MARCHIN': 168.0,
 'OOSTENDE': 169.0,
 'EUPEN': 170.0,
 'SENEFFE': 171.0,
 'WELKENRAEDT': 172.0,
 'LANGEMARK-POELKAPELLE': 173.0,
 'LIBRAMONT-CHEVIGNY': 174.0,
 'MEULEBEKE': 175.0,
 'HÉLÉCINE': 176.0,
 'PÉRUWELZ': 177.0,
 'TIENEN': 178.0,
 'GEMBLOUX': 179.0,
 'GENK': 180.0,
 'AS': 181.0,
 'BILZEN': 182.0,
 'FLOREFFE': 183.0,
 'TENNEVILLE': 184.0,
 'BERTOGNE': 185.0,
 'KINROOI': 186.0,
 'GESVES': 187.0,
 'REMICOURT': 188.0,
 'TUBIZE': 189.0,
 'PEER': 190.0,
 'DILSEN-STOKKEM': 191.0,
 'WICHELEN': 192.0,
 'MEIX-DEVANT-VIRTON': 193.0,
 'LANAKEN': 194.0,
 'BERINGEN': 195.0,
 'DURBUY': 196.0,
 'SCHERPENHEUVEL-ZICHEM': 197.0,
 'ZONNEBEKE': 198.0,
 'MALMEDY': 199.0,
 'HANNUT': 200.0,
 'HALEN': 201.0,
 'NIEUWERKERKEN': 202.0,
 'TONGEREN': 203.0,
 'DEERLIJK': 204.0,
 'SINT-LAUREINS': 205.0,
 'SINT-TRUIDEN': 206.0,
 'HOUTHALEN-HELCHTEREN': 207.0,
 'AISEAU-PRESLES': 208.0,
 'KORTESSEM': 209.0,
 'LEDEGEM': 210.0,
 'GERAARDSBERGEN': 211.0,
 'ZUTENDAAL': 212.0,
 'GANSHOREN': 213.0,
 'LOBBES': 214.0,
 'HOUYET': 215.0,
 'MERKSPLAS': 216.0,
 'DENDERLEEUW': 217.0,
 'LINCENT': 218.0,
 'SOMBREFFE': 219.0,
 'WETTEREN': 220.0,
 'BORGLOON': 221.0,
 'ORP-JAUCHE': 222.0,
 'DIEPENBEEK': 223.0,
 'EEKLO': 224.0,
 'IZEGEM': 225.0,
 'BEKKEVOORT': 226.0,
 'WIELSBEKE': 227.0,
 'OUDENBURG': 228.0,
 'ICHTEGEM': 229.0,
 'BAELEN': 230.0,
 'SILLY': 231.0,
 'BOOM': 232.0,
 'WASSEIGES': 233.0,
 'LE ROEULX': 234.0,
 'HEUSDEN-ZOLDER': 235.0,
 'OHEY': 236.0,
 'NINOVE': 237.0,
 'LEUZE-EN-HAINAUT': 238.0,
 'MOLENBEEK-SAINT-JEAN': 239.0,
 'MOL': 240.0,
 'BALEN': 241.0,
 'LENDELEDE': 242.0,
 'DENDERMONDE': 243.0,
 'MONTIGNY-LE-TILLEUL': 244.0,
 'LIEDEKERKE': 245.0,
 'ZOTTEGEM': 246.0,
 'AALST': 247.0,
 'ROESELARE': 248.0,
 'FRASNES-LEZ-ANVAING': 249.0,
 'FLOBECQ': 250.0,
 'BRAIVES': 251.0,
 'BOCHOLT': 252.0,
 'SINT-GILLIS-WAAS': 253.0,
 'CHAUDFONTAINE': 254.0,
 'CHINY': 255.0,
 'GEEL': 256.0,
 'HOUTHULST': 257.0,
 'LOMMEL': 258.0,
 'DE HAAN': 259.0,
 'JETTE': 260.0,
 'BREE': 261.0,
 'TOURNAI': 262.0,
 'LES BONS VILLERS': 263.0,
 'LINTER': 264.0,
 'KORTENAKEN': 265.0,
 'EVERE': 266.0,
 'STABROEK': 267.0,
 'OLNE': 268.0,
 'KOEKELARE': 269.0,
 'IEPER': 270.0,
 'OUDENAARDE': 271.0,
 'NIVELLES': 272.0,
 'MAASMECHELEN': 273.0,
 'SAINT-JOSSE-TEN-NOODE': 274.0,
 'ESSEN': 275.0,
 'NAMUR': 276.0,
 'STAVELOT': 277.0,
 'HAALTERT': 278.0,
 'AUBANGE': 279.0,
 'ESPIERRES-HELCHIN': 280.0,
 'LEDE': 281.0,
 'MACHELEN': 282.0,
 'TURNHOUT': 283.0,
 'WINGENE': 284.0,
 'ANDERLECHT': 285.0,
 'YVOIR': 286.0,
 'GERPINNES': 287.0,
 'LAAKDAL': 288.0,
 'TIELT': 289.0,
 'MOERBEKE-WAAS': 290.0,
 'ERPE-MERE': 291.0,
 'ANZEGEM': 292.0,
 'TORHOUT': 293.0,
 'THEUX': 294.0,
 'HERSELT': 295.0,
 'HERENTALS': 296.0,
 'RIEMST': 297.0,
 'RETIE': 298.0,
 'DESSEL': 299.0,
 'WAREGEM': 300.0,
 'HEMIKSEM': 301.0,
 'SCHELLE': 302.0,
 'HAM': 303.0,
 'TINTIGNY': 304.0,
 'TESSENDERLO': 305.0,
 'STEKENE': 306.0,
 'AARSCHOT': 307.0,
 'SPRIMONT': 308.0,
 'VILVOORDE': 309.0,
 "MONT-DE-L'ENCLUS": 310.0,
 'ARLON': 311.0,
 'AALTER': 312.0,
 'TEMSE': 313.0,
 'RAEREN': 314.0,
 'MALDEGEM': 315.0,
 'BORSBEEK': 316.0,
 'MONT-SAINT-GUIBERT': 317.0,
 'SINT-NIKLAAS': 318.0,
 'SINT-LIEVENS-HOUTEM': 319.0,
 'HAM-SUR-HEURE': 320.0,
 'NIEL': 321.0,
 'BEVEREN-WAAS': 322.0,
 'ZELE': 323.0,
 'LICHTERVELDE': 324.0,
 'KOKSIJDE': 325.0,
 'LONTZEN': 326.0,
 'NIJLEN': 327.0,
 'MORTSEL': 328.0,
 'INGELMUNSTER': 329.0,
 'LENS': 330.0,
 'BELOEIL': 331.0,
 'HABAY': 332.0,
 'DALHEM': 333.0,
 'MEERHOUT': 334.0,
 'STADEN': 335.0,
 'JURBISE': 336.0,
 'WELLIN': 337.0,
 'TIELT-WINGE': 338.0,
 'ANTWERPEN': 339.0,
 'EGHEZÉE': 340.0,
 'ASSENEDE': 341.0,
 'LOKEREN': 342.0,
 'REBECQ': 343.0,
 'PROFONDEVILLE': 344.0,
 'OUFFET': 345.0,
 'ESTAIMPUIS': 346.0,
 'AWANS': 347.0,
 'DIKSMUIDE': 348.0,
 'HAMONT-ACHEL': 349.0,
 'FAIMES': 350.0,
 'HÉRON': 351.0,
 'HOOGLEDE': 352.0,
 'HERENTHOUT': 353.0,
 'DIEST': 354.0,
 'MARTELANGE': 355.0,
 'THIMISTER-CLERMONT': 356.0,
 'LIERDE': 357.0,
 'OLEN': 358.0,
 'KLUISBERGEN': 359.0,
 'ZONHOVEN': 360.0,
 'TROIS-PONTS': 361.0,
 'INCOURT': 362.0,
 'GALMAARDEN': 363.0,
 'NIEUWPOORT': 364.0,
 'HERZELE': 365.0,
 'HAACHT': 366.0,
 'BERCHEM-SAINTE-AGATHE': 367.0,
 'LIBIN': 368.0,
 'BLÉGNY': 369.0,
 'WAIMES': 370.0,
 'BRAKEL': 371.0,
 'ALKEN': 372.0,
 'MANHAY': 373.0,
 'ARDOOIE': 374.0,
 'ETALLE': 375.0,
 'LONDERZEEL': 376.0,
 'BEERSE': 377.0,
 'VERLAINE': 378.0,
 'RAMILLIES': 379.0,
 'COURT-SAINT-ETIENNE': 380.0,
 'WILLEBROEK': 381.0,
 'PERWEZ': 382.0,
 'ROTSELAAR': 383.0,
 'HERVE': 384.0,
 'ESNEUX': 385.0,
 'TINLOT': 386.0,
 'WELLEN': 387.0,
 'LIER': 388.0,
 'EVERGEM': 389.0,
 'PUURS-SINT-AMANDS': 390.0,
 'KORTRIJK': 391.0,
 'GISTEL': 392.0,
 'ASSE': 393.0,
 'LEBBEKE': 394.0,
 'PITTEM': 395.0,
 'BEGIJNENDIJK': 396.0,
 'DUFFEL': 397.0,
 'BUTGENBACH': 398.0,
 'HALLE': 399.0,
 'CHAPELLE-LEZ-HERLAIMONT': 400.0,
 'DROGENBOS': 401.0,
 'ARENDONK': 402.0,
 'SCHAERBEEK': 403.0,
 'OOSTROZEBEKE': 404.0,
 'JUPRELLE': 405.0,
 'HERK-DE-STAD': 406.0,
 'RUMST': 407.0,
 'MAARKEDAL': 408.0,
 'LIEVEGEM': 409.0,
 'LUMMEN': 410.0,
 'LO-RENINGE': 411.0,
 'HASSELT': 412.0,
 'MERCHTEM': 413.0,
 'ALVERINGEM': 414.0,
 'BERLOZ': 415.0,
 'EDEGEM': 416.0,
 'PUTTE': 417.0,
 'NANDRIN': 418.0,
 'WACHTEBEKE': 419.0,
 'ZWALM': 420.0,
 'VORSELAAR': 421.0,
 'WESTERLO': 422.0,
 'NAZARETH': 423.0,
 'SAINT-LÉGER': 424.0,
 'GOUVY': 425.0,
 'MAASEIK': 426.0,
 'ASSESSE': 427.0,
 'WOMMELGEM': 428.0,
 'VILLERS-LA-VILLE': 429.0,
 'ZEDELGEM': 430.0,
 'VEURNE': 431.0,
 'MESSANCY': 432.0,
 'PELT': 433.0,
 'ROOSDAAL': 434.0,
 'WUUSTWEZEL': 435.0,
 'HAMOIS': 436.0,
 'MALLE': 437.0,
 'GRIMBERGEN': 438.0,
 'KRUIBEKE': 439.0,
 'BRAINE-LE-CHÂTEAU': 440.0,
 'MOORSLEDE': 441.0,
 'WALHAIN': 442.0,
 'BORNEM': 443.0,
 'DEINZE': 444.0,
 'AFFLIGEM': 445.0,
 'HEIST-OP-DEN-BERG': 446.0,
 'OOSTERZELE': 447.0,
 'TREMELO': 448.0,
 'SINT-KATELIJNE-WAVER': 449.0,
 'LINT': 450.0,
 'ZANDHOVEN': 451.0,
 'LILLE': 452.0,
 'GAVERE': 453.0,
 'BERLARE': 454.0,
 'SINT-PIETERS-LEEUW': 455.0,
 'ZWIJNDRECHT': 456.0,
 'BUGGENHOUT': 457.0,
 'BRUGGE': 458.0,
 'ZULTE': 459.0,
 'FOURONS': 460.0,
 'HULSHOUT': 461.0,
 'JABBEKE': 462.0,
 'RUISELEDE': 463.0,
 'GROBBENDONK': 464.0,
 'MERELBEKE': 465.0,
 'LEUVEN': 466.0,
 'LA BRUYÈRE': 467.0,
 'KONTICH': 468.0,
 'ITTRE': 469.0,
 'CHASTRE': 470.0,
 'FERNELMONT': 471.0,
 'SCHOTEN': 472.0,
 'ENGHIEN': 473.0,
 'FOREST': 474.0,
 'STOUMONT': 475.0,
 'NEUPRÉ': 476.0,
 'OPWIJK': 477.0,
 'GLABBEEK': 478.0,
 'MECHELEN': 479.0,
 'LUBBEEK': 480.0,
 'AUBEL': 481.0,
 'OOSTKAMP': 482.0,
 'BEERNEM': 483.0,
 'BOORTMEERBEEK': 484.0,
 'DAVERDISSE': 485.0,
 'BOUTERSEM': 486.0,
 'DILBEEK': 487.0,
 "BRAINE-L'ALLEUD": 488.0,
 'JODOIGNE': 489.0,
 'WAVRE': 490.0,
 'GENT': 491.0,
 'BEERSEL': 492.0,
 'BRUNEHAUT': 493.0,
 'ZAVENTEM': 494.0,
 'HERNE': 495.0,
 'LIERNEUX': 496.0,
 'TERNAT': 497.0,
 'BRUXELLES': 498.0,
 'BOECHOUT': 499.0,
 'KAPELLE-OP-DEN-BOS': 500.0,
 'LAARNE': 501.0,
 'HOOGSTRATEN': 502.0,
 'GOOIK': 503.0,
 'GENAPPE': 504.0,
 'BERLAAR': 505.0,
 'MELLE': 506.0,
 'DENTERGEM': 507.0,
 'JALHAY': 508.0,
 'AARTSELAAR': 509.0,
 'HOEGAARDEN': 510.0,
 'KRUISEM': 511.0,
 'WORTEGEM-PETEGEM': 512.0,
 'BERTEM': 513.0,
 'BRECHT': 514.0,
 'OTTIGNIES-LOUVAIN-LA-NEUVE': 515.0,
 'VOSSELAAR': 516.0,
 'HOVE': 517.0,
 'HERENT': 518.0,
 'KASTERLEE': 519.0,
 'SPA': 520.0,
 'WEMMEL': 521.0,
 'LOCHRISTI': 522.0,
 'ZEMST': 523.0,
 'MEISE': 524.0,
 'HOLSBEEK': 525.0,
 'KAPELLEN': 526.0,
 'RANST': 527.0,
 'BRASSCHAAT': 528.0,
 'KAPRIJKE': 529.0,
 'ZOERSEL': 530.0,
 'OUD-TURNHOUT': 531.0,
 'RIJKEVORSEL': 532.0,
 'ATTERT': 533.0,
 'WIJNEGEM': 534.0,
 'HOREBEKE': 535.0,
 'COMINES-WARNETON': 536.0,
 'LA HULPE': 537.0,
 'KALMTHOUT': 538.0,
 'WOLUWE-SAINT-LAMBERT': 539.0,
 'ETTERBEEK': 540.0,
 'KEERBERGEN': 541.0,
 'DAMME': 542.0,
 'STEENOKKERZEEL': 543.0,
 'BEAUVECHAIN': 544.0,
 'AUDERGHEM': 545.0,
 'RAVELS': 546.0,
 'GREZ-DOICEAU': 547.0,
 'UCCLE': 548.0,
 'DESTELBERGEN': 549.0,
 'SAINT-GILLES': 550.0,
 'HOEILAART': 551.0,
 'WEZEMBEEK-OPPEM': 552.0,
 'KORTENBERG': 553.0,
 'LENNIK': 554.0,
 'LINKEBEEK': 555.0,
 'KAMPENHOUT': 556.0,
 'OUD-HEVERLEE': 557.0,
 'WATERLOO': 558.0,
 'BONHEIDEN': 559.0,
 'DE PINTE': 560.0,
 'ZUIENKERKE': 561.0,
 'BIERBEEK': 562.0,
 'CHAUMONT-GISTOUX': 563.0,
 'IXELLES': 564.0,
 'HULDENBERG': 565.0,
 'BIÉVÈNE': 566.0,
 'WAASMUNSTER': 567.0,
 'RIXENSART': 568.0,
 'SCHILDE': 569.0,
 'OVERIJSE': 570.0,
 'TERVUREN': 571.0,
 'RHODE-SAINT-GENÈSE': 572.0,
 'KNOKKE-HEIST': 573.0,
 'WOLUWE-SAINT-PIERRE': 574.0,
 'WATERMAEL-BOITSFORT': 575.0,
 'PEPINGEN': 576.0,
 'KRAAINEM': 577.0,
 'BAARLE-HERTOG': 578.0,
 'SINT-MARTENS-LATEM': 579.0,
 'LASNE': 580.0}

###### Subtype of property

In [42]:
# Subtype of property is related to the property's type.

print_unique_dtype(immo, 'subtype_of_property')
immo.subtype_of_property.value_counts()

24 - object

house                   54101
apartment               37592
villa                    7449
duplex                   3596
ground floor             2693
mixed use building       2264
apartment block          2074
penthouse                1810
flat studio              1429
exceptional property     1292
mansion                  1259
country cottage          1078
service flat              820
town house                795
bungalow                  681
loft                      534
chalet                    513
farmhouse                 424
manor house               235
other property            166
triplex                   152
kot                        84
castle                     27
pavilion                    3
Name: subtype_of_property, dtype: int64

In [43]:
# Drop castle & pavilion.
immo = immo[(immo['subtype_of_property'] != 'castle') & 
        (immo['subtype_of_property'] != 'pavilion') & 
        (immo['subtype_of_property'] != 'apartment block')]

print_unique_dtype(immo, 'subtype_of_property')
immo.shape

21 - object

(118967, 21)

###### Price

In [44]:
print_unique_dtype(immo, 'price')

257 - int64

In [45]:
immo.price.describe()

count    118967.000000
mean     296958.438306
std      159604.920651
min        2500.000000
25%      193000.000000
50%      260000.000000
75%      350000.000000
max      950000.000000
Name: price, dtype: float64

In [46]:
immo[immo['price'] == 2500]

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,terrace_area,...,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,construction_year,locality,commune,province,region
22343,1400,apartment,apartment,2500,3,90,1,0,1,4,...,0,0,4,0,as new,1978,Monstreux,NIVELLES,Brabant Wallon,Région flamande
22344,1400,apartment,apartment,2500,3,90,1,0,1,4,...,0,0,4,0,as new,1978,NIVELLES,NIVELLES,Brabant Wallon,Région flamande
96474,2530,house,exceptional property,2500,5,600,1,1,1,60,...,1750,1750,4,0,as new,1842,BOECHOUT,BOECHOUT,Anvers,Région flamande
109180,6960,house,other property,2500,3,154,1,1,1,18,...,3000,3000,4,0,as new,2006,Vaux-Chavanne,MANHAY,Luxembourg,Région wallonne
109181,6960,house,other property,2500,3,154,1,1,1,18,...,3000,3000,4,0,as new,2006,MANHAY,MANHAY,Luxembourg,Région wallonne
109182,6960,house,other property,2500,3,154,1,1,1,18,...,3000,3000,4,0,as new,2006,Odeigne,MANHAY,Luxembourg,Région wallonne
109183,6960,house,other property,2500,3,154,1,1,1,18,...,3000,3000,4,0,as new,2006,Harre,MANHAY,Luxembourg,Région wallonne
109184,6960,house,other property,2500,3,154,1,1,1,18,...,3000,3000,4,0,as new,2006,Dochamps,MANHAY,Luxembourg,Région wallonne
109185,6960,house,other property,2500,3,154,1,1,1,18,...,3000,3000,4,0,as new,2006,Malempré,MANHAY,Luxembourg,Région wallonne
109186,6960,house,other property,2500,3,154,1,1,1,18,...,3000,3000,4,0,as new,2006,Grandménil,MANHAY,Luxembourg,Région wallonne

In [47]:
# Remove too much lower price, taking in consideration the house area
immo = immo[(immo['price'] > 10000)]
immo = immo[(immo['price'] > 35000) | (immo['house_area'] < 80)]

In [48]:
immo.price.describe()

count    118726.000000
mean     297515.466368
std      159286.249961
min       11825.000000
25%      194500.000000
50%      260000.000000
75%      350000.000000
max      950000.000000
Name: price, dtype: float64

In [49]:
immo[immo['price'] < 30000]

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,terrace_area,...,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,construction_year,locality,commune,province,region
4068,4000,apartment,ground floor,28000,2,25,0,0,0,0,...,0,0,1,0,NaN,<NA>,Glain,LIÈGE,Liège,Région wallonne
4069,4000,apartment,ground floor,28000,2,25,0,0,0,0,...,0,0,1,0,NaN,<NA>,LIÈGE,LIÈGE,Liège,Région wallonne
4070,4000,apartment,ground floor,28000,2,25,0,0,0,0,...,0,0,1,0,NaN,<NA>,Rocourt,LIÈGE,Liège,Région wallonne
23317,8301,apartment,flat studio,20000,0,42,0,0,0,0,...,0,0,2,1,to renovate,1971,Ramskapelle,KNOKKE-HEIST,Flandre-Occidentale,Région flamande
23318,8301,apartment,flat studio,20000,0,42,0,0,0,0,...,0,0,2,1,to renovate,1971,Heist-Aan-Zee,KNOKKE-HEIST,Flandre-Occidentale,Région flamande
24640,8400,apartment,apartment,25000,2,72,1,0,1,5,...,0,0,2,0,good,1994,Stene,OOSTENDE,Flandre-Occidentale,Région flamande
24641,8400,apartment,apartment,25000,2,72,1,0,1,5,...,0,0,2,0,good,1994,OOSTENDE,OOSTENDE,Flandre-Occidentale,Région flamande
24642,8400,apartment,apartment,25000,2,72,1,0,1,5,...,0,0,2,0,good,1994,Zandvoorde,OOSTENDE,Flandre-Occidentale,Région flamande
86546,6740,apartment,kot,14500,1,28,1,0,0,0,...,0,0,4,0,good,2015,ETALLE,ETALLE,Luxembourg,Région wallonne
86547,6740,apartment,kot,14500,1,28,1,0,0,0,...,0,0,4,0,good,2015,Villers-Sur-Semois,ETALLE,Luxembourg,Région wallonne
86548,6740,apartment,kot,14500,1,28,1,0,0,0,...,0,0,4,0,good,2015,Sainte-Marie-Sur-Semois,ETALLE,Luxembourg,Région wallonne
99029,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Patignies,GEDINNE,Namur,Région wallonne
99030,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Sart-Custinne,GEDINNE,Namur,Région wallonne
99031,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Bourseigne-Vieille,GEDINNE,Namur,Région wallonne
99032,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Bourseigne-Neuve,GEDINNE,Namur,Région wallonne
99033,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Louette-Saint-Denis,GEDINNE,Namur,Région wallonne
99034,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Malvoisin,GEDINNE,Namur,Région wallonne
99035,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Vencimont,GEDINNE,Namur,Région wallonne
99036,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,GEDINNE,GEDINNE,Namur,Région wallonne
99037,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Louette-Saint-Pierre,GEDINNE,Namur,Région wallonne
99038,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Houdremont,GEDINNE,Namur,Région wallonne
99039,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Willerzie,GEDINNE,Namur,Région wallonne
99040,5575,house,chalet,28500,1,36,1,0,0,0,...,0,264,4,0,NaN,<NA>,Rienne,GEDINNE,Namur,Région wallonne
111755,5540,house,chalet,25000,1,60,1,0,0,0,...,0,215,4,0,to renovate,<NA>,HASTIÈRE,HASTIÈRE,Namur,Région wallonne
111756,5540,house,chalet,25000,1,60,1,0,0,0,...,0,215,4,0,to renovate,<NA>,Hastière-Lavaux,HASTIÈRE,Namur,Région wallonne
111757,5540,house,chalet,25000,1,60,1,0,0,0,...,0,215,4,0,to renovate,<NA>,Hermeton-Sur-Meuse,HASTIÈRE,Namur,Région wallonne
111758,5540,house,chalet,25000,1,60,1,0,0,0,...,0,215,4,0,to renovate,<NA>,Waulsort,HASTIÈRE,Namur,Région wallonne
112621,6041,house,house,29900,2,70,1,0,0,0,...,0,41,2,0,to renovate,1874,Gosselies,CHARLEROI,Hainaut,Région wallonne
117016,3111,house,house,11825,1,13,0,0,0,0,...,0,13,2,0,as new,2017,Wezemaal,ROTSELAAR,Brabant Flamand,Région flamande
118866,6464,house,house,20000,2,45,1,0,1,15,...,120,200,4,0,NaN,<NA>,Rièzes,CHIMAY,Hainaut,Région wallonne
118867,6464,house,house,20000,2,45,1,0,1,15,...,120,200,4,0,NaN,<NA>,Bourlers,CHIMAY,Hainaut,Région wallonne
118868,6464,house,house,20000,2,45,1,0,1,15,...,120,200,4,0,NaN,<NA>,Forges,CHIMAY,Hainaut,Région wallonne
118869,6464,house,house,20000,2,45,1,0,1,15,...,120,200,4,0,NaN,<NA>,Baileux,CHIMAY,Hainaut,Région wallonne
118870,6464,house,house,20000,2,45,1,0,1,15,...,120,200,4,0,NaN,<NA>,L'Escaillère,CHIMAY,Hainaut,Région wallonne

###### Number of rooms

In [50]:
immo.number_of_rooms.describe()

count    118723.000000
mean          2.871609
std           2.107251
min           0.000000
25%           2.000000
50%           3.000000
75%           3.000000
max         204.000000
Name: number_of_rooms, dtype: float64

In [51]:
immo.number_of_rooms.value_counts()

3      40110
2      37856
4      18216
1      10547
5       6277
6       2494
0       1654
7        721
8        363
9        137
10       120
11        79
12        31
15        31
14        22
13        18
20        12
16         9
24         7
30         5
204        5
165        4
23         4
18         1
Name: number_of_rooms, dtype: Int64

In [52]:
# Remove number_of_rooms >= 165
immo = immo[immo['number_of_rooms'] < 165]
immo.number_of_rooms.value_counts()

3     40110
2     37856
4     18216
1     10547
5      6277
6      2494
0      1654
7       721
8       363
9       137
10      120
11       79
12       31
15       31
14       22
13       18
20       12
16        9
24        7
30        5
23        4
18        1
Name: number_of_rooms, dtype: Int64

###### House Area

In [53]:
immo.house_area.value_counts()

150     2506
120     2491
100     2375
140     2293
90      2271
        ...
613        1
710        1
551        1
488        1
1407       1
Name: house_area, Length: 676, dtype: int64

In [54]:
immo.house_area.describe()

count    118714.000000
mean        159.199884
std         138.829265
min           1.000000
25%          95.000000
50%         135.000000
75%         191.000000
max       31700.000000
Name: house_area, dtype: float64

In [55]:
immo[immo['house_area'] < 15]

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,terrace_area,...,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,construction_year,locality,commune,province,region
5445,4540,apartment,apartment,185000,2,11,0,0,1,5,...,0,0,3,0,as new,<NA>,Ombret,AMAY,Liège,Région wallonne
5446,4540,apartment,apartment,185000,2,11,0,0,1,5,...,0,0,3,0,as new,<NA>,Flône,AMAY,Liège,Région wallonne
5447,4540,apartment,apartment,185000,2,11,0,0,1,5,...,0,0,3,0,as new,<NA>,Ampsin,AMAY,Liège,Région wallonne
5448,4540,apartment,apartment,185000,2,11,0,0,1,5,...,0,0,3,0,as new,<NA>,Jehay,AMAY,Liège,Région wallonne
5449,4540,apartment,apartment,185000,2,11,0,0,1,5,...,0,0,3,0,as new,<NA>,AMAY,AMAY,Liège,Région wallonne
26368,8400,apartment,apartment,425000,2,1,0,0,1,0,...,0,0,2,0,good,1961,Stene,OOSTENDE,Flandre-Occidentale,Région flamande
26369,8400,apartment,apartment,425000,2,1,0,0,1,0,...,0,0,2,0,good,1961,OOSTENDE,OOSTENDE,Flandre-Occidentale,Région flamande
26370,8400,apartment,apartment,425000,2,1,0,0,1,0,...,0,0,2,0,good,1961,Zandvoorde,OOSTENDE,Flandre-Occidentale,Région flamande
40705,2800,apartment,kot,99000,1,14,0,0,0,0,...,0,0,2,0,NaN,2014,Walem,MECHELEN,Anvers,Région flamande
40706,2800,apartment,kot,99000,1,14,0,0,0,0,...,0,0,2,0,NaN,2014,MECHELEN,MECHELEN,Anvers,Région flamande
51018,3290,apartment,apartment,265000,2,1,0,0,0,0,...,0,0,<NA>,0,NaN,<NA>,DIEST,DIEST,Brabant Flamand,Région flamande
51019,3290,apartment,apartment,265000,2,1,0,0,0,0,...,0,0,<NA>,0,NaN,<NA>,Webbekom,DIEST,Brabant Flamand,Région flamande
51020,3290,apartment,apartment,265000,2,1,0,0,0,0,...,0,0,<NA>,0,NaN,<NA>,Schaffen,DIEST,Brabant Flamand,Région flamande
51021,3290,apartment,apartment,265000,2,1,0,0,0,0,...,0,0,<NA>,0,NaN,<NA>,Deurne,DIEST,Brabant Flamand,Région flamande
62210,8870,apartment,apartment,125000,4,5,0,0,0,0,...,0,0,<NA>,0,as new,<NA>,Kachtem,IZEGEM,Flandre-Occidentale,Région flamande
62211,8870,apartment,apartment,125000,4,5,0,0,0,0,...,0,0,<NA>,0,as new,<NA>,Emelgem,IZEGEM,Flandre-Occidentale,Région flamande
62212,8870,apartment,apartment,125000,4,5,0,0,0,0,...,0,0,<NA>,0,as new,<NA>,IZEGEM,IZEGEM,Flandre-Occidentale,Région flamande
78944,4845,house,villa,323000,4,1,0,0,1,0,...,0,913,<NA>,0,as new,2013,JALHAY,JALHAY,Liège,Région wallonne
78945,4845,house,villa,323000,4,1,0,0,1,0,...,0,913,<NA>,0,as new,2013,Sart-Lez-Spa,JALHAY,Liège,Région wallonne
78948,4845,house,villa,307000,3,1,0,0,0,0,...,500,0,4,0,as new,2019,JALHAY,JALHAY,Liège,Région wallonne
78949,4845,house,villa,307000,3,1,0,0,0,0,...,500,0,4,0,as new,2019,Sart-Lez-Spa,JALHAY,Liège,Région wallonne
82146,9340,apartment,penthouse,297500,3,13,0,0,1,0,...,0,0,<NA>,0,NaN,2018,LEDE,LEDE,Flandre-Orientale,Région flamande
82147,9340,apartment,penthouse,297500,3,13,0,0,1,0,...,0,0,<NA>,0,NaN,2018,Oordegem,LEDE,Flandre-Orientale,Région flamande
82148,9340,apartment,penthouse,297500,3,13,0,0,1,0,...,0,0,<NA>,0,NaN,2018,Impe,LEDE,Flandre-Orientale,Région flamande
82149,9340,apartment,penthouse,297500,3,13,0,0,1,0,...,0,0,<NA>,0,NaN,2018,Wanzele,LEDE,Flandre-Orientale,Région flamande
82150,9340,apartment,penthouse,297500,3,13,0,0,1,0,...,0,0,<NA>,0,NaN,2018,Smetlede,LEDE,Flandre-Orientale,Région flamande
87943,2000,apartment,kot,115000,1,14,1,0,1,0,...,0,0,<NA>,0,good,<NA>,ANTWERPEN,ANTWERPEN,Anvers,Région flamande
100331,8791,house,house,335000,4,5,1,0,0,0,...,0,484,<NA>,0,good,1956,Beveren,WAREGEM,Flandre-Occidentale,Région flamande
105373,8840,apartment,apartment,135000,0,5,0,0,0,0,...,0,0,<NA>,0,good,<NA>,STADEN,STADEN,Flandre-Occidentale,Région flamande
105374,8840,apartment,apartment,135000,0,5,0,0,0,0,...,0,0,<NA>,0,good,<NA>,Oostnieuwkerke,STADEN,Flandre-Occidentale,Région flamande
105375,8840,apartment,apartment,135000,0,5,0,0,0,0,...,0,0,<NA>,0,good,<NA>,Westrozebeke,STADEN,Flandre-Occidentale,Région flamande
117016,3111,house,house,11825,1,13,0,0,0,0,...,0,13,2,0,as new,2017,Wezemaal,ROTSELAAR,Brabant Flamand,Région flamande
117444,8954,house,house,265500,3,5,1,0,0,0,...,0,373,<NA>,0,as new,2019,Westouter,HEUVELLAND,Flandre-Occidentale,Région flamande

In [56]:
immo[immo['house_area'] > 1500]

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,terrace_area,...,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,construction_year,locality,commune,province,region
24383,9600,house,house,650000,1,1640,0,0,0,0,...,0,1640,3,0,good,1991,RENAIX,RENAIX,Flandre-Orientale,Région flamande
26623,8400,house,house,219000,4,2019,0,0,0,0,...,0,165,2,0,NaN,<NA>,Stene,OOSTENDE,Flandre-Occidentale,Région flamande
26624,8400,house,house,219000,4,2019,0,0,0,0,...,0,165,2,0,NaN,<NA>,OOSTENDE,OOSTENDE,Flandre-Occidentale,Région flamande
26625,8400,house,house,219000,4,2019,0,0,0,0,...,0,165,2,0,NaN,<NA>,Zandvoorde,OOSTENDE,Flandre-Occidentale,Région flamande
46420,7050,house,mixed use building,175000,2,1700,0,0,0,0,...,0,1700,4,0,to renovate,<NA>,JURBISE,JURBISE,Hainaut,Région wallonne
46421,7050,house,mixed use building,175000,2,1700,0,0,0,0,...,0,1700,4,0,to renovate,<NA>,Herchies,JURBISE,Hainaut,Région wallonne
46422,7050,house,mixed use building,175000,2,1700,0,0,0,0,...,0,1700,4,0,to renovate,<NA>,Erbisoeul,JURBISE,Hainaut,Région wallonne
46423,7050,house,mixed use building,175000,2,1700,0,0,0,0,...,0,1700,4,0,to renovate,<NA>,Masnuy-Saint-Jean,JURBISE,Hainaut,Région wallonne
46424,7050,house,mixed use building,175000,2,1700,0,0,0,0,...,0,1700,4,0,to renovate,<NA>,Masnuy-Saint-Pierre,JURBISE,Hainaut,Région wallonne
46425,7050,house,mixed use building,175000,2,1700,0,0,0,0,...,0,1700,4,0,to renovate,<NA>,Erbaut,JURBISE,Hainaut,Région wallonne
57863,6200,house,mixed use building,399000,0,1525,0,0,0,0,...,0,790,2,0,good,<NA>,Bouffioulx,CHÂTELET,Hainaut,Région wallonne
57864,6200,house,mixed use building,399000,0,1525,0,0,0,0,...,0,790,2,0,good,<NA>,CHÂTELET,CHÂTELET,Hainaut,Région wallonne
57865,6200,house,mixed use building,399000,0,1525,0,0,0,0,...,0,790,2,0,good,<NA>,Châtelineau,CHÂTELET,Hainaut,Région wallonne
64963,2880,house,manor house,750000,3,3560,1,1,1,24,...,3560,3560,4,0,good,1979,Hingene,BORNEM,Anvers,Région flamande
64964,2880,house,manor house,750000,3,3560,1,1,1,24,...,3560,3560,4,0,good,1979,Mariekerke,BORNEM,Anvers,Région flamande
64965,2880,house,manor house,750000,3,3560,1,1,1,24,...,3560,3560,4,0,good,1979,Weert,BORNEM,Anvers,Région flamande
64966,2880,house,manor house,750000,3,3560,1,1,1,24,...,3560,3560,4,0,good,1979,BORNEM,BORNEM,Anvers,Région flamande
82912,3000,apartment,kot,250000,1,31700,1,0,1,0,...,0,0,<NA>,0,as new,<NA>,LEUVEN,LEUVEN,Brabant Flamand,Région flamande
95384,7140,house,mixed use building,360000,0,1900,0,0,1,0,...,0,0,3,0,NaN,<NA>,Morlanwelz-Mariemont,MORLANWELZ,Hainaut,Région wallonne
95385,7140,house,mixed use building,360000,0,1900,0,0,1,0,...,0,0,3,0,NaN,<NA>,MORLANWELZ,MORLANWELZ,Hainaut,Région wallonne
112538,6698,house,country cottage,399000,0,2562,0,0,0,0,...,0,100144,4,0,NaN,<NA>,Grand-Halleux,VIELSALM,Luxembourg,Région wallonne

In [57]:
# Drop too small and too big house_area, taking the price in consideration
immo = immo[(immo['house_area'] > 10) & 
            ((immo['house_area'] < 1000) | ((immo['house_area'] > 1000) & (immo['price'] > 390000)))]

In [58]:
immo.shape

(118646, 21)

###### Surface of the Land

In [59]:
immo.surface_of_the_land.describe()

count    118646.000000
mean        684.000877
std        4434.701449
min           0.000000
25%           0.000000
50%         118.000000
75%         563.750000
max      400000.000000
Name: surface_of_the_land, dtype: float64

In [60]:
immo[immo['surface_of_the_land'] == 0]

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,terrace_area,...,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,construction_year,locality,commune,province,region
5,1050,house,house,590000,4,225,0,0,1,0,...,0,0,2,0,to renovate,<NA>,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
6,1050,house,house,575000,4,209,1,0,0,0,...,0,0,2,0,NaN,<NA>,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
16,1050,house,house,685000,6,280,1,0,0,0,...,0,0,2,0,NaN,1956,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
25,1050,house,house,795000,4,240,1,0,1,8,...,59,0,2,0,good,1907,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
30,1050,house,house,795000,8,240,1,0,0,0,...,0,0,2,0,good,<NA>,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120954,5022,house,house,240000,2,230,0,0,0,0,...,0,0,3,0,as new,1885,Cognelée,NAMUR,Namur,Région wallonne
120968,6221,house,house,210000,2,131,1,0,1,0,...,0,0,3,0,good,<NA>,Saint-Amand,FLEURUS,Hainaut,Région wallonne
121001,6723,house,house,385000,3,201,0,0,1,25,...,111,0,2,0,as new,2020,Habay-La-Vieille,HABAY,Luxembourg,Région wallonne
121058,4342,house,house,425000,3,315,1,0,1,124,...,250,0,3,0,NaN,2002,Hognoul,AWANS,Liège,Région wallonne
121064,3050,house,house,435000,4,234,1,0,1,20,...,0,0,3,0,as new,<NA>,OUD-HEVERLEE,OUD-HEVERLEE,Brabant Flamand,Région flamande

In [61]:
immo[(immo['surface_of_the_land']<2) & (immo['garden_area']>2)]

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,terrace_area,...,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,construction_year,locality,commune,province,region
25,1050,house,house,795000,4,240,1,0,1,8,...,59,0,2,0,good,1907,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
69,1050,apartment,flat studio,220000,0,49,1,0,0,0,...,23,0,2,0,as new,2019,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
74,1050,apartment,flat studio,220000,0,49,1,0,0,0,...,35,0,<NA>,0,as new,2019,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
149,1050,apartment,ground floor,395000,2,91,1,0,1,15,...,20,0,<NA>,0,good,1979,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
185,1050,apartment,ground floor,440000,1,85,0,0,1,0,...,70,0,<NA>,0,good,<NA>,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120309,4560,house,farmhouse,199000,4,195,1,0,0,0,...,500,0,3,0,to be done up,1899,Pailhe,CLAVIER,Liège,Région wallonne
120310,4560,house,farmhouse,199000,4,195,1,0,0,0,...,500,0,3,0,to be done up,1899,Ocquier,CLAVIER,Liège,Région wallonne
120311,4560,house,farmhouse,199000,4,195,1,0,0,0,...,500,0,3,0,to be done up,1899,Terwagne,CLAVIER,Liège,Région wallonne
121001,6723,house,house,385000,3,201,0,0,1,25,...,111,0,2,0,as new,2020,Habay-La-Vieille,HABAY,Luxembourg,Région wallonne
121058,4342,house,house,425000,3,315,1,0,1,124,...,250,0,3,0,NaN,2002,Hognoul,AWANS,Liège,Région wallonne

In [62]:
immototal = pd.DataFrame()
immototal = immo[(immo['surface_of_the_land']<2) & (immo['garden_area']>2)]
immototal['surface_of_the_land'] = immototal['house_area'] + immototal['terrace_area'] + immototal['garden_area']
immototal

<ipython-input-62-e3256665fe8b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  immototal['surface_of_the_land'] = immototal['house_area'] + immototal['terrace_area'] + immototal['garden_area']

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,terrace_area,...,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,construction_year,locality,commune,province,region
25,1050,house,house,795000,4,240,1,0,1,8,...,59,307,2,0,good,1907,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
69,1050,apartment,flat studio,220000,0,49,1,0,0,0,...,23,72,2,0,as new,2019,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
74,1050,apartment,flat studio,220000,0,49,1,0,0,0,...,35,84,<NA>,0,as new,2019,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
149,1050,apartment,ground floor,395000,2,91,1,0,1,15,...,20,126,<NA>,0,good,1979,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
185,1050,apartment,ground floor,440000,1,85,0,0,1,0,...,70,155,<NA>,0,good,<NA>,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120309,4560,house,farmhouse,199000,4,195,1,0,0,0,...,500,695,3,0,to be done up,1899,Pailhe,CLAVIER,Liège,Région wallonne
120310,4560,house,farmhouse,199000,4,195,1,0,0,0,...,500,695,3,0,to be done up,1899,Ocquier,CLAVIER,Liège,Région wallonne
120311,4560,house,farmhouse,199000,4,195,1,0,0,0,...,500,695,3,0,to be done up,1899,Terwagne,CLAVIER,Liège,Région wallonne
121001,6723,house,house,385000,3,201,0,0,1,25,...,111,337,2,0,as new,2020,Habay-La-Vieille,HABAY,Luxembourg,Région wallonne
121058,4342,house,house,425000,3,315,1,0,1,124,...,250,689,3,0,NaN,2002,Hognoul,AWANS,Liège,Région wallonne

In [63]:
# Taking off all rows with the surface of the land missing
immo = immo[immo['surface_of_the_land']>5]
immo.shape

(64669, 21)

In [64]:
immo = pd.concat([immo, immototal], axis=0)
immo.shape

(68844, 21)

###### State of the building

In [65]:
# State of the building data has 'None'
immo.state_of_the_building.value_counts()

good              19585
as new            15290
to renovate        6646
to be done up      6544
just renovated     3709
to restore          485
Name: state_of_the_building, dtype: int64

In [66]:
immo['state_of_the_building'] = immo['state_of_the_building'].fillna('unknown')
immo.state_of_the_building.value_counts()

good              19585
unknown           16585
as new            15290
to renovate        6646
to be done up      6544
just renovated     3709
to restore          485
Name: state_of_the_building, dtype: int64

In [67]:
immo.state_of_the_building.describe()

count     68844
unique        7
top        good
freq      19585
Name: state_of_the_building, dtype: object

###### Kitchen

###### Open Fire

###### Terrace

###### Terrace Area

In [68]:
immo.subtype_of_property.value_counts()

house                   50335
villa                    7258
apartment                2097
mixed use building       1922
exceptional property     1224
mansion                  1163
country cottage          1033
ground floor              836
town house                713
bungalow                  666
chalet                    494
farmhouse                 415
manor house               235
duplex                    228
other property            124
penthouse                  29
flat studio                21
loft                       20
service flat               17
triplex                    14
Name: subtype_of_property, dtype: int64

In [69]:
immo[immo['type_of_property'] == 'house'].subtype_of_property.value_counts()

house                   50335
villa                    7258
mixed use building       1922
exceptional property     1224
mansion                  1163
country cottage          1033
town house                713
bungalow                  666
chalet                    494
farmhouse                 415
manor house               235
other property            124
Name: subtype_of_property, dtype: int64

In [70]:
immo[immo['type_of_property'] != 'house'].subtype_of_property.value_counts()

apartment       2097
ground floor     836
duplex           228
penthouse         29
flat studio       21
loft              20
service flat      17
triplex           14
Name: subtype_of_property, dtype: int64

In [71]:
immo[immo['surface_of_the_land'] == 0]

Empty DataFrame
Columns: [zip, type_of_property, subtype_of_property, price, number_of_rooms, house_area, fully_equipped_kitchen, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building, construction_year, locality, commune, province, region]
Index: []

[0 rows x 21 columns]

###### Garden

###### Garden Area

###### Number of facades

In [72]:
immo.number_of_facades.value_counts()

4    23027
2    18511
3    17622
1      344
Name: number_of_facades, dtype: Int64

In [73]:
immo.isna().sum()

zip                           0
type_of_property              0
subtype_of_property           0
price                         0
number_of_rooms               0
house_area                    0
fully_equipped_kitchen        0
open_fire                     0
terrace                       0
terrace_area                  0
garden                        0
garden_area                   0
surface_of_the_land           0
number_of_facades          9340
swimming_pool                 0
state_of_the_building         0
construction_year         30157
locality                      0
commune                       0
province                      0
region                        0
dtype: int64

In [74]:
# filling with median value
immo['number_of_facades'] = immo['number_of_facades'].fillna(3)
immo.number_of_facades.value_counts()

3    26962
4    23027
2    18511
1      344
Name: number_of_facades, dtype: Int64

###### Swimming pool

In [75]:
immo.swimming_pool.value_counts()

0    67004
1     1840
Name: swimming_pool, dtype: int64

###### Construction year

In [76]:
immo.shape

(68844, 21)

In [77]:
immo.reset_index(drop=True, inplace=True)
immo.shape

(68844, 21)

In [78]:
immo = immo.drop(["fully_equipped_kitchen", "open_fire", "terrace", "terrace_area", 
                  "garden", "garden_area", "construction_year"], axis=1)
immo

,zip,type_of_property,subtype_of_property,price,number_of_rooms,house_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,locality,commune,province,region
0,1050,house,house,340000,6,203,95,2,0,to be done up,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
1,1050,house,mixed use building,520000,4,200,69,2,0,to renovate,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
2,1050,house,house,599000,4,160,100,2,0,to be done up,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
3,1050,house,house,599000,3,160,130,2,0,good,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
4,1050,house,house,575000,3,171,46,2,0,just renovated,IXELLES,IXELLES,Bruxelles (19 communes),Région Bruxelles-capitale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68839,4560,house,farmhouse,199000,4,195,695,3,0,to be done up,Pailhe,CLAVIER,Liège,Région wallonne
68840,4560,house,farmhouse,199000,4,195,695,3,0,to be done up,Ocquier,CLAVIER,Liège,Région wallonne
68841,4560,house,farmhouse,199000,4,195,695,3,0,to be done up,Terwagne,CLAVIER,Liège,Région wallonne
68842,6723,house,house,385000,3,201,337,2,0,as new,Habay-La-Vieille,HABAY,Luxembourg,Région wallonne
68843,4342,house,house,425000,3,315,689,3,0,unknown,Hognoul,AWANS,Liège,Région wallonne

In [79]:
immo.to_csv('../../Datasets/clean_immo.csv', index=False)